// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzgZRSFL9G9lHhH3jpoRjJvZ6OBSgLHCI',
    appId: '1:487387356408:web:d150bd57426c9ecf446f0d',
    messagingSenderId: '487387356408',
    projectId: 'todo-c42f9',
    authDomain: 'todo-c42f9.firebaseapp.com',
    storageBucket: 'todo-c42f9.appspot.com',
    measurementId: 'G-FJ5WPB0LWF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3goVoO0JbYNuN_uCBWhnVbViGXDmBJ3g',
    appId: '1:487387356408:android:d07c2f4d52615332446f0d',
    messagingSenderId: '487387356408',
    projectId: 'todo-c42f9',
    storageBucket: 'todo-c42f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA06s2ZV9d3UoQAzH8jm2wkFl9JBq82lt0',
    appId: '1:487387356408:ios:3dfb5f9893b4758f446f0d',
    messagingSenderId: '487387356408',
    projectId: 'todo-c42f9',
    storageBucket: 'todo-c42f9.appspot.com',
    iosClientId: '487387356408-ullpvsmslg8dd5thbh29kbvqot9vegb5.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA06s2ZV9d3UoQAzH8jm2wkFl9JBq82lt0',
    appId: '1:487387356408:ios:21d324ddad979379446f0d',
    messagingSenderId: '487387356408',
    projectId: 'todo-c42f9',
    storageBucket: 'todo-c42f9.appspot.com',
    iosClientId: '487387356408-t43bs7rlv1df4gn60u4glguhir6fn6s4.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo.RunnerTests',
  );
}
